CREATE OR REPLACE PROCEDURE SP_AGREGARANUNCIO(TITULO_IN IN VARCHAR, DETALLE_IN IN VARCHAR, TIPO_IN IN NUMBER, USR_CREACION_IN IN VARCHAR, RESULTADO_OUT OUT NUMBER)
IS
    SQL_ERRORCODE INT;
    SQL_ERRORMESSAGE VARCHAR(1500);
BEGIN
    INSERT INTO EVENTO(ID_EVENTO, TITULO, DETALLE, TIPO, FECHA_INS, ESTADO, USR_CREACION) VALUES
        ((SELECT NVL(MAX(ID_EVENTO),0)+1 FROM EVENTO), TITULO_IN, DETALLE_IN, TIPO_IN, CURRENT_TIMESTAMP, 'A', USR_CREACION_IN);
    RESULTADO_OUT :=0;
EXCEPTION WHEN OTHERS THEN
    SQL_ERRORMESSAGE:=SQLERRM;
    SQL_ERRORCODE:= SQLCODE;
    RESULTADO_OUT :=-1;
    INSERT INTO ERROR(ID_ERROR, PROCESO, COD_ERROR, MENSAJE_ERROR, FECHA) VALUES
                    ((SELECT NVL(MAX(ID_ERROR), 0)+1 FROM ERROR), 'SP_AGREGARANUNCIO',SQL_ERRORCODE,SQL_ERRORMESSAGE, CURRENT_TIMESTAMP );
    COMMIT;
END;