CREATE OR REPLACE PROCEDURE SP_CALCULARNOTA1SEMESTRE(RUN_IN IN NUMBER, ID_ASIGNATURA_IN IN NUMBER, RESULTADO_OUT OUT VARCHAR)
IS 
    SQL_ERRORCODE INT;
    SQL_ERRORMESSAGE VARCHAR(1500);
    SUMA_NOTAS NUMBER;
    COUNT_NOTAS NUMBER;
BEGIN 
    SUMA_NOTAS:=F_SUMARNOTASS2(RUN_IN, ID_ASIGNATURA_IN);
    COUNT_NOTAS:=F_CONTARNOTASS2(RUN_IN, ID_ASIGNATURA_IN);
    UPDATE NOTA SET P2 = ROUND(SUMA_NOTAS/COUNT_NOTAS, 1) WHERE ID_ASIGNATURA = ID_ASIGNATURA_IN AND RUN = RUN_IN;
    RESULTADO_OUT :=0;
EXCEPTION WHEN OTHERS THEN
    SQL_ERRORMESSAGE:=SQLERRM;
    SQL_ERRORCODE:= SQLCODE;
    RESULTADO_OUT :=-1;
    INSERT INTO ERROR(ID_ERROR, PROCESO, COD_ERROR, MENSAJE_ERROR, FECHA) VALUES
                    ((SELECT NVL(MAX(ID_ERROR), 0)+1 FROM ERROR), 'SP_CALCULARNOTA1SEMESTRE',SQL_ERRORCODE,SQL_ERRORMESSAGE, CURRENT_TIMESTAMP );
    COMMIT;

END;
