CREATE OR REPLACE PROCEDURE SP_DESACTIVARSALA(ID_SALA_IN NUMBER, RESULTADO_OUT OUT NUMBER)
IS
BEGIN
    UPDATE SALA SET ESTADO = 'X' WHERE ID_SALA = ID_SALA_IN AND ESTADO = 'A';
    COMMIT;
    RESULTADO_OUT:= 0;
EXCEPTION 
WHEN OTHERS THEN
    ROLLBACK;
    RESULTADO_OUT:= -1;
END;