CREATE OR REPLACE PROCEDURE SP_ELIMINARALUMNODECURSO(RUN_IN IN INT, RESULTADO_OUT OUT NUMBER)
AS
BEGIN
    UPDATE PERSONA SET ID_CURSO=NULL WHERE RUN = RUN_IN AND ESTADO = 'A';
    COMMIT;
    RESULTADO_OUT:=0;
EXCEPTION
WHEN OTHERS THEN
    ROLLBACK;
    RESULTADO_OUT:=-1;
END;