CREATE OR REPLACE PROCEDURE SP_GETPARAMETRO(PARAMETRO_IN IN NUMBER, RESULTADO_OUT OUT NUMBER)
IS
    SQL_ERRORCODE INT;
    SQL_ERRORMESSAGE VARCHAR(1500);

BEGIN
    SELECT VALOR INTO RESULTADO_OUT FROM PARAMS WHERE ID_PARAM = PARAMETRO_IN;

EXCEPTION WHEN NO_DATA_FOUND THEN
    RESULTADO_OUT:= -2;
WHEN OTHERS THEN
    SQL_ERRORMESSAGE:=SQLERRM;
    SQL_ERRORCODE:= SQLCODE;
    RESULTADO_OUT:= -1;
    
    INSERT INTO ERROR(ID_ERROR, PROCESO, COD_ERROR, MENSAJE_ERROR, FECHA) VALUES
                    ((SELECT NVL(MAX(ID_ERROR), 0)+1 FROM ERROR), 'F_GETPARAMETRO',SQL_ERRORCODE,SQL_ERRORMESSAGE, CURRENT_TIMESTAMP );
    COMMIT;
END;