CREATE OR REPLACE PROCEDURE SP_GUARDAR_CREDENCIALES(RUN_IN NUMBER, COD_USUARIO_IN VARCHAR, MAIL_IN VARCHAR, PASSWORD_IN VARCHAR)

IS
/*ZONA DECLARATIVA DE VARIABLES*/

BEGIN
    /*CUERPO DE LA FUNCION*/
    INSERT INTO USUARIO(RUN, COD_USUARIO, MAIL, PASSWORD, ESTADO ) VALUES (RUN_IN, LOWER(COD_USUARIO_IN), MAIL_IN, PASSWORD_IN, 'A');

END;	