CREATE OR REPLACE PROCEDURE SP_INSERTARMATRICULA(RUN_IN IN NUMBER, ANIO_IN IN NUMBER, USR_CREACION_IN IN VARCHAR2, NIVEL_IN IN INT, RESULTADO_OUT OUT NUMBER)  
IS
/*v1.0 Adolfo Montes*/
   RES_VAR NUMBER;
   UPDATE_MATRICULA NUMBER;
BEGIN
    INSERT INTO MATRICULA (NUM_MATRICULA, ANIO, FEC_MATRICULA, ESTADO, USR_CREACION, NIVEL) 
                    VALUES((SELECT NVL(MAX(NUM_MATRICULA), 0)+1 FROM MATRICULA), ANIO_IN, CURRENT_TIMESTAMP, 'A', USR_CREACION_IN, NIVEL_IN)
                    RETURNING (SELECT NVL(MAX(NUM_MATRICULA), 0)+1 FROM MATRICULA) INTO RESULTADO_OUT;
                    --UPDATE_MATRICULA:=F_INSERTAR_MATRICULA(RUN_IN, RESULTADO_OUT);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE(UPDATE_MATRICULA);
EXCEPTION
WHEN OTHERS THEN
    RESULTADO_OUT:=-1;
    ROLLBACK;
END;