CREATE OR REPLACE PROCEDURE SP_INSERTARRUTALUMNOAPODERADO(RUNALUMNO_IN IN NUMBER, RUN_APODERADO_IN IN NUMBER, RESULTADO_OUT OUT NUMBER)
IS 
BEGIN
	INSERT INTO PERSONA_APODERADO(RUN, RUN_APODERADO) VALUES (RUNALUMNO_IN, RUN_APODERADO_IN);
	COMMIT;
	RESULTADO_OUT:=0;

EXCEPTION
WHEN OTHERS THEN
	RESULTADO_OUT:=1;
END;