CREATE OR REPLACE PROCEDURE SP_INSERTARAPODERADO(RUN_IN IN NUMBER, DV_IN IN CHAR, PRI_NOM_IN IN VARCHAR2, SEG_NOM_IN IN VARCHAR2, PRI_AP_IN IN VARCHAR2,
                                                SEG_AP_IN IN VARCHAR2, OCUPACION_IN IN NUMBER, ESTADO_CIVIL_IN IN NUMBER, PARENTESCO_IN IN NUMBER,
                                                MAIL_IN IN VARCHAR2, TELEFONO_IN IN VARCHAR2, FEC_NAC_IN IN DATE, NIVEL_IN IN NUMBER, DIRECCION_IN IN VARCHAR2,
                                                COMUNA_IN IN NUMBER, RESULTADO_OUT OUT NUMBER)
IS
    EXISTE_APODERADO NUMBER;
    DIRECCION_RESPUESTA NUMBER;
    err_num NUMBER;
    err_msg VARCHAR2(255);
BEGIN
    EXISTE_APODERADO:=F_VALIDAR_APODERADO(RUN_IN);
    IF EXISTE_APODERADO = 0 THEN   --APODERADO NO EXISTE, SE GUARDA
        SP_INSERTARDIRECCION(DIRECCION_IN, COMUNA_IN, DIRECCION_RESPUESTA); --GUARDAMOS DIRECCION --ok
        INSERT INTO APODERADO (RUN, DV, PRI_NOM, SEG_NOM, PRI_AP, SEG_AP, FEC_NAC, TELEFONO, MAIL, ESTADO, ID_NIVEL, ID_ESTADOCIVIL, ID_DIRECCION,
                            ID_OCUPACION, ID_PARENTESCO, ID_COMUNA)
                    VALUES(RUN_IN, DV_IN, PRI_NOM_IN, SEG_NOM_IN,PRI_AP_IN, SEG_AP_IN, FEC_NAC_IN, TELEFONO_IN, MAIL_IN, 'A', NIVEL_IN, ESTADO_CIVIL_IN, DIRECCION_RESPUESTA,
                            OCUPACION_IN, PARENTESCO_IN, COMUNA_IN);
        
         RESULTADO_OUT:=0;
    ELSE
        RESULTADO_OUT:= EXISTE_APODERADO;--APODERADO EXISTE
    END IF;
   COMMIT;
EXCEPTION 
WHEN OTHERS THEN
     err_num := SQLCODE;
    err_msg := SQLERRM;
    DBMS_OUTPUT.put_line('Error:'||TO_CHAR(err_num));
    DBMS_OUTPUT.put_line(err_msg);
    RESULTADO_OUT:=2; --ERROR NO ESPECIFICADO
    ROLLBACK;
END;