CREATE OR REPLACE PROCEDURE SP_INSERTARCURSO(ID_NIVEL_IN IN INT, CODIGO_IN IN VARCHAR2, NOMBRECURSO_IN IN VARCHAR2, 
											CANTIDADMAX_IN IN NUMBER, ANIO_IN IN NUMBER, ID_DOCENTE_IN IN NUMBER, RESULTADO_OUT OUT NUMBER)
IS 
VALIDADOR_CURSO VARCHAR2(1500);
v_codigo_error    NUMBER;
v_mensaje_error   VARCHAR2(1500);
BEGIN
	VALIDADOR_CURSO:=F_VALIDARCURSO(CODIGO_IN, ID_NIVEL_IN, ANIO_IN);

    IF VALIDADOR_CURSO = 0 THEN
        	INSERT INTO CURSO(ID_CURSO, COD_CURSO, NOM_CURSO, CANTIDAD_MAX, ID_NIVEL, ANIO, ID_DOCENTE, ESTADO) 
                    VALUES ((SELECT NVL(MAX(ID_CURSO), 0) +1 FROM CURSO), CODIGO_IN, NOMBRECURSO_IN, CANTIDADMAX_IN, ID_NIVEL_IN, ANIO_IN, 
                    REPLACE(ID_DOCENTE_IN, 0, null), 'A');
                    
        COMMIT;
        RESULTADO_OUT:=0;
    ELSE
        RESULTADO_OUT:=1;
    END IF;

EXCEPTION 
WHEN OTHERS THEN
	ROLLBACK;
	v_codigo_error := SQLCODE;
    v_mensaje_error :=  SQLERRM;
	RESULTADO_OUT:=v_mensaje_error;
END;