CREATE OR REPLACE FUNCTION F_VALIDAREXISTENCIAASIGNATURA(COD_ASIGNATURA_IN VARCHAR2) RETURN NUMBER
IS
	VALIDADOR NUMBER;
BEGIN	
	SELECT ID_ASIGNATURA INTO VALIDADOR FROM ASIGNATURA WHERE COD_ASIGNATURA = COD_ASIGNATURA_IN;
	IF VALIDADOR>0 THEN
		RETURN -2;
	ELSE 
		RETURN 0;
	END IF;

EXCEPTION WHEN NO_DATA_FOUND THEN
	RETURN 0;
WHEN OTHERS THEN 
	RETURN -1;
END; 