CREATE OR REPLACE FUNCTION F_VALIDARSIESALUMNO(RUN_IN NUMBER) RETURN NUMBER
IS 
    VALIDADOR_ALUMNO INT;
    SQL_ERRORCODE INT;
    SQL_ERRORMESSAGE VARCHAR(1500);
BEGIN
    SELECT RUN INTO VALIDADOR_ALUMNO FROM PERSONA WHERE RUN = RUN_IN AND ID_ROL = 5 AND ESTADO = 'A' AND ID_CURSO IS NOT NULL;
    RETURN VALIDADOR_ALUMNO;
EXCEPTION WHEN NO_DATA_FOUND THEN
    VALIDADOR_ALUMNO:= -1;
    RETURN VALIDADOR_ALUMNO;
WHEN OTHERS THEN 
    SQL_ERRORMESSAGE:=SQLERRM;
    SQL_ERRORCODE:= SQLCODE;
    INSERT INTO ERROR(ID_ERROR, PROCESO, COD_ERROR, MENSAJE_ERROR, FECHA) VALUES
                    ((SELECT NVL(MAX(ID_ERROR), 0)+1 FROM ERROR), 'F_VALIDARSIESALUMNO',SQL_ERRORCODE,SQL_ERRORMESSAGE, CURRENT_TIMESTAMP );
    COMMIT;    
    RETURN -1;
END;