CREATE OR REPLACE FUNCTION F_VALIDAR_USUARIO(USUARIO_IN VARCHAR2) RETURN NUMBER
IS
/*ZONA DECLARATIVA DE VARIABLES*/
USUARIO_VAR VARCHAR2(50);
RES_VAR NUMBER;
BEGIN
    /*CUERPO DE LA FUNCION*/
    SELECT COD_USUARIO INTO USUARIO_VAR FROM USUARIO WHERE LOWER(COD_USUARIO) = LOWER(USUARIO_IN) ;
    IF USUARIO_VAR IS NULL THEN
        RES_VAR:= 0;
    ELSE 
        RES_VAR:=1;
    END IF;
    RETURN RES_VAR;
EXCEPTION
WHEN NO_DATA_FOUND THEN
    RES_VAR:=0;
    RETURN RES_VAR;
WHEN OTHERS THEN
    RES_VAR:= 1;
    RETURN RES_VAR; 
    
END;
