CREATE OR REPLACE FUNCTION F_VALIDARNOTASEMESTRE(RUN_IN NUMBER, ANIO_IN NUMBER, ID_ASIGNATURA_IN NUMBER) RETURN NUMBER
IS
    VALIDADOR_NOTA NUMBER;
    SQL_ERRORCODE INT;
    SQL_ERRORMESSAGE VARCHAR(1500);
BEGIN
    SELECT ID_NOTA INTO VALIDADOR_NOTA FROM NOTA WHERE ID_ASIGNATURA = ID_ASIGNATURA_IN AND RUN= RUN_IN AND ANIO=ANIO_IN;
    IF (VALIDADOR_NOTA IS NULL) THEN
        VALIDADOR_NOTA := 0; -- NO HAY NOTAS, DEBO INSERTAR
    END IF;
    RETURN VALIDADOR_NOTA; -- SI VALIDADOR_NOTA >1 ENTONCES DEBO UPDATEAR USANDO ESE ID_NOTA
EXCEPTION WHEN NO_DATA_FOUND THEN
    VALIDADOR_NOTA:=0; -- NO HAY NOTAS, POR ENDE DEBO INSERTAR
WHEN OTHERS THEN
    VALIDADOR_NOTA:=-1;
    SQL_ERRORMESSAGE:=SQLERRM;
    SQL_ERRORCODE:= SQLCODE;

    INSERT INTO ERROR(ID_ERROR, PROCESO, COD_ERROR, MENSAJE_ERROR, FECHA) VALUES
                    ((SELECT NVL(MAX(ID_ERROR), 0)+1 FROM ERROR), 'F_VALIDARNOTASEMESTRE',SQL_ERRORCODE,SQL_ERRORMESSAGE, CURRENT_TIMESTAMP );
    COMMIT;
    RETURN VALIDADOR_NOTA;
END;